services:
  - type: web
    name: sports-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p 8000 webapi.asgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: webapi.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ALLOWED_HOSTS
        value: "sports-app.onrender.com"
      - key: REDIS_URL
        fromService:
          name: sports-redis
          type: redis

  - type: redis
    name: sports-redis
    ipAllowList: []
    plan: free
