# Generated by Django 5.1.4 on 2025-08-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClubStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='sports.club')),
            ],
        ),
        migrations.CreateModel(
            name='MatchFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='sports.club')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='sports.club')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_a', models.PositiveIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_as_team_a', to='sports.club')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_as_team_b', to='sports.club')),
            ],
        ),
    ]
