# Generated by Django 5.1.4 on 2025-08-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_player_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='score_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='score_b',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='sports.matchresult')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.player')),
            ],
        ),
    ]
