# Generated by Django 5.1.4 on 2025-08-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
