# Generated by Django 5.1.4 on 2025-08-13 09:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_delete_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
