# Generated by Django 5.1.4 on 2025-08-17 18:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_alter_club_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='appearances',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='goals',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('gk', 'Goalkeeper'), ('rb', 'Right Back'), ('rcb', 'Right Center Back'), ('cb', 'Center Back'), ('lcb', 'Left Center Back'), ('lb', 'Left Back'), ('cdm', 'Central Defensive Midfielder'), ('rm', 'Right Midfielder'), ('cm', 'Central Midfielder'), ('lm', 'Left Midfielder'), ('cam', 'Central Attacking Midfielder'), ('rw', 'Right Winger'), ('lw', 'Left Winger'), ('cf', 'Center Forward'), ('st', 'Striker'), ('ss', 'Second Striker'), ('utility', 'Utility Player')], max_length=50, null=True),
        ),
    ]
