# Generated by Django 5.1.4 on 2025-08-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_clubnewsarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubnewsarticle',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_news', to='sports.club'),
        ),
    ]
