# Generated by Django 5.1.4 on 2025-08-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_clubsubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
